// Snapshot serialization (T1.5, security gate G1). Turns a ResolvedEnv into the
// sourceable `snapshot.zsh` text (design §5). This file is a product of the core, not
// a second implementation.
//
// THE security invariant (#2): a secret is emitted as
//   export NAME="$(envcue keychain-get --account 'ACCOUNT')"
// The plaintext key NEVER appears here — only the account reference, which is not
// secret. The real value travels through the `$(...)` stdout pipe into the shell at
// source time, never into argv or history.

import Foundation

public extension EnvCueCore {
    /// Serialize `env` into sourceable zsh text.
    ///
    /// - `activeScene` is only used for the one-shot `_ENVCUE_NOTICE` label (`base`
    ///   when nil). It is intentionally NOT part of the generation fingerprint in the
    ///   header (invariant #5): the header embeds `generation(env)`, computed from
    ///   content alone.
    /// - `previousNames` are the variable names the *previously committed* snapshot
    ///   exported (read from the prior `manifest.json` by the caller). Any name present
    ///   then but absent from `env` now is emitted as a trailing `unset`, so an
    ///   already-open shell that re-sources this snapshot drops the variables that left
    ///   with the old scene — including secrets (PROPOSAL-004). New shells are unaffected
    ///   (those names were never exported). This set equals `diff(previous, env).removed`
    ///   by construction, keeping the snapshot's cleanup in lock-step with the change
    ///   preview the user confirmed. It does NOT enter the generation fingerprint
    ///   (PROPOSAL-004 §3.2a): generation stays a function of `env` content alone, so two
    ///   scenes that resolve to the same env share a generation regardless of history.
    static func serialize(
        _ env: ResolvedEnv,
        activeScene: String?,
        previousNames: Set<String> = []
    ) -> String {
        var lines: [String] = []
        lines.append("# AUTO-GENERATED by envcue — do not edit. generation=\(generation(env))")

        for v in env.vars { // sorted by name
            switch v.entry.kind {
            case .plain:
                lines.append("export \(v.entry.name)=\"\(escapeDoubleQuoted(v.entry.value ?? ""))\"")
            case .secret:
                let account = escapeSingleQuoted(v.entry.account ?? "")
                lines.append("export \(v.entry.name)=\"$(envcue keychain-get --account '\(account)')\"")
            case .unset:
                lines.append("unset \(v.entry.name) 2>/dev/null")
            }
        }

        // Cleanup: variables the previous snapshot exported that this env no longer has.
        // Names are validated at load (PROPOSAL-001), so they need no escaping here — the
        // same form the `.unset` branch above uses. Sorted for deterministic output.
        let currentNames = Set(env.vars.map { $0.entry.name })
        let goneNames = previousNames.subtracting(currentNames).sorted()
        if !goneNames.isEmpty {
            lines.append("# envcue: clear variables carried over from the previous scene")
            for name in goneNames {
                lines.append("unset \(name) 2>/dev/null")
            }
        }

        let label = escapeSingleQuoted(activeScene ?? "base")
        lines.append("_ENVCUE_NOTICE='%F{cyan}envcue%f → \(label)'")

        return lines.joined(separator: "\n") + "\n"
    }

    /// Escape for inside double quotes: backslash, double quote, `$`, and backtick — so
    /// a plain value is exported literally and cannot trigger expansion or substitution.
    private static func escapeDoubleQuoted(_ s: String) -> String {
        var out = ""
        out.reserveCapacity(s.count)
        for ch in s {
            switch ch {
            case "\\": out += "\\\\"
            case "\"": out += "\\\""
            case "$": out += "\\$"
            case "`": out += "\\`"
            default: out.append(ch)
            }
        }
        return out
    }

    /// Escape for inside single quotes using the `'\''` idiom. Defensive: accounts and
    /// scene names are `{layer}/{VAR}`-shaped and normally need no escaping.
    private static func escapeSingleQuoted(_ s: String) -> String {
        s.replacingOccurrences(of: "'", with: "'\\''")
    }
}
