// Snapshot serialization (T1.5, security gate G1). Turns a ResolvedEnv into the
// sourceable `snapshot.zsh` text (design §5). This file is a product of the core, not
// a second implementation.
//
// THE security invariant (#2): a secret is emitted as
//   export NAME="$(envcue keychain-get --account 'ACCOUNT')"
// The plaintext key NEVER appears here — only the account reference, which is not
// secret. The real value travels through the `$(...)` stdout pipe into the shell at
// source time, never into argv or history.

import Foundation

public extension EnvCueCore {
    /// Serialize `env` into sourceable zsh text.
    ///
    /// - `activeScene` is only used for the one-shot `_ENVCUE_NOTICE` label (`base`
    ///   when nil). It is intentionally NOT part of the generation fingerprint in the
    ///   header (invariant #5): the header embeds `generation(env)`, computed from
    ///   content alone.
    static func serialize(_ env: ResolvedEnv, activeScene: String?) -> String {
        var lines: [String] = []
        lines.append("# AUTO-GENERATED by envcue — do not edit. generation=\(generation(env))")

        for v in env.vars { // sorted by name
            switch v.entry.kind {
            case .plain:
                lines.append("export \(v.entry.name)=\"\(escapeDoubleQuoted(v.entry.value ?? ""))\"")
            case .secret:
                let account = escapeSingleQuoted(v.entry.account ?? "")
                lines.append("export \(v.entry.name)=\"$(envcue keychain-get --account '\(account)')\"")
            case .unset:
                lines.append("unset \(v.entry.name) 2>/dev/null")
            }
        }

        let label = escapeSingleQuoted(activeScene ?? "base")
        lines.append("_ENVCUE_NOTICE='%F{cyan}envcue%f → \(label)'")

        return lines.joined(separator: "\n") + "\n"
    }

    /// Escape for inside double quotes: backslash, double quote, `$`, and backtick — so
    /// a plain value is exported literally and cannot trigger expansion or substitution.
    private static func escapeDoubleQuoted(_ s: String) -> String {
        var out = ""
        out.reserveCapacity(s.count)
        for ch in s {
            switch ch {
            case "\\": out += "\\\\"
            case "\"": out += "\\\""
            case "$": out += "\\$"
            case "`": out += "\\`"
            default: out.append(ch)
            }
        }
        return out
    }

    /// Escape for inside single quotes using the `'\''` idiom. Defensive: accounts and
    /// scene names are `{layer}/{VAR}`-shaped and normally need no escaping.
    private static func escapeSingleQuoted(_ s: String) -> String {
        s.replacingOccurrences(of: "'", with: "'\\''")
    }
}
